// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectChanges(arg1, arg2) {
  return window['go']['uiapi']['API']['DetectChanges'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['uiapi']['API']['SetContext'](arg1);
}
