// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {main} from '../models';

export function DiffJSON(arg1:string):Promise<string>;

export function GetDiffForProject(arg1:string):Promise<string>;

export function ListRemoteProjects():Promise<Array<backend.ProjectDoc>>;

export function PendingJSON(arg1:string):Promise<string>;

export function PickRoot():Promise<string>;

export function Pull(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function Push(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Rollback(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RootStats(arg1:string):Promise<main.RootStatsResult>;

export function ScanJSON(arg1:string):Promise<string>;

export function ScanProjects(arg1:string):Promise<Array<backend.AbletonProject>>;

export function StartWatcherAll(arg1:string,arg2:boolean):Promise<void>;

export function StopWatcherAll():Promise<void>;
