// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiffJSON(arg1) {
  return window['go']['main']['App']['DiffJSON'](arg1);
}

export function DiffProjectJSON(arg1, arg2) {
  return window['go']['main']['App']['DiffProjectJSON'](arg1, arg2);
}

export function GetDiffForProject(arg1) {
  return window['go']['main']['App']['GetDiffForProject'](arg1);
}

export function ListRemoteProjects() {
  return window['go']['main']['App']['ListRemoteProjects']();
}

export function PendingJSON(arg1) {
  return window['go']['main']['App']['PendingJSON'](arg1);
}

export function PickRoot() {
  return window['go']['main']['App']['PickRoot']();
}

export function Pull(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Pull'](arg1, arg2, arg3, arg4);
}

export function Push(arg1, arg2, arg3) {
  return window['go']['main']['App']['Push'](arg1, arg2, arg3);
}

export function Rollback(arg1, arg2, arg3) {
  return window['go']['main']['App']['Rollback'](arg1, arg2, arg3);
}

export function RootStats(arg1) {
  return window['go']['main']['App']['RootStats'](arg1);
}

export function ScanJSON(arg1) {
  return window['go']['main']['App']['ScanJSON'](arg1);
}

export function ScanProjects(arg1) {
  return window['go']['main']['App']['ScanProjects'](arg1);
}

export function StartWatcherAll(arg1, arg2) {
  return window['go']['main']['App']['StartWatcherAll'](arg1, arg2);
}

export function StopWatcherAll() {
  return window['go']['main']['App']['StopWatcherAll']();
}
